# Generated by Django 6.0.3 on 2026-06-12 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='accent_color',
            field=models.CharField(choices=[('purple', 'Purple'), ('blue', 'Blue'), ('cyan', 'Cyan'), ('green', 'Green'), ('orange', 'Orange'), ('red', 'Red'), ('pink', 'Pink')], default='cyan', max_length=20),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='animations_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='density',
            field=models.CharField(choices=[('comfortable', 'Comfortable'), ('compact', 'Compact')], default='comfortable', max_length=20),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='sidebar_behavior',
            field=models.CharField(choices=[('expanded', 'Expanded'), ('collapsed', 'Collapsed')], default='expanded', max_length=20),
        ),
    ]
