# Generated by Django 6.0.3 on 2026-08-12 00:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewCard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "card_type",
                    models.CharField(
                        choices=[
                            ("basic", "Basic"),
                            ("cloze", "Cloze"),
                            ("image_occlusion", "Image occlusion"),
                            ("qa", "Q&A"),
                        ],
                        default="basic",
                        max_length=20,
                    ),
                ),
                ("question", models.TextField()),
                ("answer", models.TextField()),
                ("hint", models.TextField(blank=True)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("interval_minutes", models.PositiveIntegerField(default=0)),
                ("repetitions", models.PositiveIntegerField(default=0)),
                ("ease_factor", models.FloatField(default=2.5)),
                ("lapses", models.PositiveIntegerField(default=0)),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deck",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cards",
                        to="reviews.reviewdeck",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
