# Generated by Django 6.0.3 on 2026-08-12 00:09

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0002_reviewcard"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        choices=[
                            ("again", "Again"),
                            ("hard", "Hard"),
                            ("good", "Good"),
                            ("easy", "Easy"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("interval_before", models.PositiveIntegerField()),
                ("interval_after", models.PositiveIntegerField()),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_logs",
                        to="reviews.reviewcard",
                    ),
                ),
            ],
            options={
                "ordering": ["-reviewed_at"],
            },
        ),
    ]
