# Generated by Django 6.0.3 on 2026-08-15 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0003_reviewlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviewcard",
            name="answer_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="reviewcard",
            name="question_description",
            field=models.TextField(blank=True),
        ),
    ]
