# Generated by Django 6.0.3 on 2026-08-15 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0004_reviewcard_answer_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviewcard",
            name="answer_description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="reviewcard",
            name="question_description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
