# Generated by Django 6.0.3 on 2026-08-15 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0005_alter_reviewcard_answer_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviewcard",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
    ]
