# Generated by Django 6.0.3 on 2026-03-18 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_course_owner_studyarea_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyarea',
            name='slug',
            field=models.SlugField(),
        ),
    ]
