# Generated by Django 6.0.3 on 2026-03-10 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_module_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='status',
        ),
        migrations.AddField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='planned', max_length=20),
        ),
    ]
