# Generated by Django 6.0.3 on 2026-08-16 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0003_alter_studyarea_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("active", "Active"),
                    ("completed", "Completed"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
